FROM python:3.11-slim

WORKDIR /app

COPY requirements-fastapi.txt /app/requirements-fastapi.txt

RUN pip3 install -r requirements-fastapi.txt

EXPOSE 8000

CMD ["uvicorn", "remote_bank:app", "--host", "0.0.0.0", "--port", "8000" ,"--reload"]
